version: '3.8'

networks:
  loki-net:

volumes:
  prometheus-data: {}
  alertmanager-data: {}
  grafana-data: {}

services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    network_mode: host
    pid: host 
    volumes:
      - '/:/host:ro,rslave'
    command:
      - '--path.rootfs=/host'

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/rules.yml:/etc/prometheus/rules.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    ports: 
      - '9090:9090'

  alertmanager:
    image: quay.io/prometheus/alertmanager:latest
    container_name: alertmanager
    restart: unless-stopped
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager-data:/alertmanager
    command: 
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    ports:
      - '9093:9093'
  
  loki:
    image: grafana/loki:latest
    container_name: loki
    volumes:
      - ./loki/loki.yml:/etc/loki/loki.yml
    command:
      - '--config.file=/etc/loki/loki.yml'
    ports:
      - "3100:3100"
    networks:
      - loki-net
    
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - ./promtail/promtail.yml:/etc/promtail/promtail.yml
    command: 
      - '--config.file=/etc/promtail/promtail.yml'
    networks:
      - loki-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    volumes:
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - 'grafana-data:/var/lib/grafana'
    ports:
      - "3000:3000"
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
    networks:
      - loki-net