global:
  scrape_interval: 15s
  evaluation_interval: 15s 

rule_files:
  - 'rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['172.17.0.1:9093']
      
scrape_configs:
  - job_name: cadvisor
    static_configs:
    - targets: ['172.17.0.1:8080']